### ISSUE TITLE
Outdated client

### ISSUE THREAD

**Issue by dotnetemmanuel** [sohrabhamza/sheep-it-on-colab#3]
the client is outdated and needs to be updated

**Comment by jonybabe1** [comment]
change the download URL sheep client version 
 in `https://www.sheepit-renderfarm.com/media/applet/sheepit-client-6.21338.0.jar`
 to `6.22164.0`
It solves the Outdated Client  Issue and you can Close the issue after that.

**Comment by sohrabhamza** [comment]
Fixed, 
Sorry for the late fix, I am not at home. Also I do not use this actively.
