### ISSUE TITLE
GPU Acceleration changed to Optix, causes error

### ISSUE THREAD

**Issue by smsahil71485** [sohrabhamza/sheep-it-on-colab#8]
The new client has been updated to use Optix and HIP as GPU accelerators, so CUDA doesn't work with the current code. 
Is it possible to fix this? I am not a programmer, so I don't understand any of this.
Here is the error that is shown in the "Run this to start" cell:

ERROR: The entered GPU_ID is invalid. The GPU_ID should look like 'OPTIX_#' or 'HIP_#'. Please use the proper GPU_ID from the GPU list below

Nvidia::getGpus driver version too old: 460.32.03

Thank you, kind sir. Have a nice day.

**Comment by sohrabhamza** [comment]
I looked through it and it seems that sheepit no longer supports CUDA. 
Unfortunately most of the GPUs available with colab do not support optix.
I can't find any way to get it working rn, so will have to wait for colab to update their drivers.

**Comment by Raimund58** [comment]
It is working again. Take a look https://colab.research.google.com/gist/Raimund58/685ec8da663c2bbcc954c4af711f97dd/sheepit_gpu.ipynb

**Comment by smsahil71485** [comment]
> It is working again. Take a look https://colab.research.google.com/gist/Raimund58/685ec8da663c2bbcc954c4af711f97dd/sheepit_gpu.ipynb

Thank you so much! Colab GPU is working now.

**Comment by sohrabhamza** [comment]
> It is working again. Take a look https://colab.research.google.com/gist/Raimund58/685ec8da663c2bbcc954c4af711f97dd/sheepit_gpu.ipynb

HI, Thank you for the fix. I implemented it into the notebook. 
Also you should remove the username and key from your link
