### ISSUE TITLE
I might've found a fix for Sheep it on colab 

### ISSUE THREAD

**Issue by Yezgen** [sohrabhamza/sheep-it-on-colab#9]
Greetings, 
firstly, I want to thank you for sharing this great code, it really saves me a lot of time and energy.

Last night I found out they updated Colab and the code doesn't operate properly any more.

I tried a few things, but the only solution that worked for me (So far) is this:
I changed the last cell from

`if computemethod == "CPU":
    !java -jar $sheepitversion -ui oneLine/text -cache-dir /content/cache -compute-method $computemethod -login $username -password $key -ui text
else:
    !java -jar $sheepitversion -ui oneLine/text -cache-dir /content/cache -compute-method GPU -gpu CUDA_0 -login $username -password $key -ui text`

To 

`if computemethod == "CPU":
    !java -jar $sheepitversion -ui oneLine/text -cache-dir /content/cache -compute-method $computemethod -login $username -password $key -ui text
else:
    !java -jar $sheepitversion -ui oneLine/text -cache-dir /content/cache -compute-method GPU -gpu OPTIX_0 -login $username -password $key -ui text`

You have Probably fixed it already, but for those who haven't yet, I hope this works for you, cheers.

**Comment by sohrabhamza** [comment]
Thanks, this almost fixed it. Complete fix implemented thanks to Raimund58
